
language: node_js
cache:
  directories:
    - 'node_modules'
    - ~/.npm
notifications:
  email: mindreeper2420@gmail.com
node_js:
  - '10'
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "mindreeper2420@gmail.com"
    - TRIGGER_REPO_SLUG: "mindreeper2420/rhd-frontend-pattern.library.github.io"
    - TRIGGER_REPO_BRANCH: "master"
before_script:
  - npm install -g gulp-cli
script: gulp
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
